### ISSUE TITLE
Add examples back to the Readme.

### ISSUE THREAD

**Issue by t-persson** [eiffel-community/eiffel-pythonlib#1]
### Description
Examples broke when uploading to github and they had to be removed when uploading to Pypi.
They need to be re-added

### Motivation
Simple examples need to be added for people to start using the library.

### Exemplification
Easy to start with copy-pastable examples.

### Benefits
Easy to start.

### Possible Drawbacks
They need to be updated if the interface changes.

**Comment by fredjn** [comment]
Please define what you mean by broke? Du you have any logs of what actually went wrong?

**Comment by t-persson** [comment]
@fredjn they did not show up at all on github and pypi upload crashed with a parsing error. No logs at the moment

**Comment by fredjn** [comment]
Fixed here: https://github.com/eiffel-community/eiffel-pythonlib/pull/2
