### ISSUE TITLE
Routing key for published events should follow Sepia recommendation

### ISSUE THREAD

**Issue by magnusbaeck** [eiffel-community/eiffel-pythonlib#36]
### Description
Nowadays Sepia specifies a [recommended routing key for Eiffel events published on a RabbitMQ bus](https://eiffel-community.github.io/eiffel-sepia/rabbitmq-message-broker.html). This library should be capable of following that standard.

It's not clear how this feature should be introduced; the default routing key in the kwarg to the [RabbitMQPublisher](https://github.com/eiffel-community/eiffel-pythonlib/blob/main/eiffellib/publishers/rabbitmq_publisher.py) constructor is "eiffel" and we can't change that willy-nilly without introducing a backwards incompatibility. Perhaps we could make None a magic kwarg value that means "follow the Sepia recommendation". When we make the next major version bump we can flip the kwarg default to None.

### Motivation
With a routing key that isn't a fixed string but actually includes the event type clients will have a much easier time filtering out events that aren't interesting to them.

### Exemplification
A client only interested in, say, CD won't have to throw away the magnitudes-large stream of test-related events from ETOS (for example).

### Benefits
Possible for consumers to set up queue bindings so that they're not overwhelmed by uninteresting events.

### Possible Drawbacks
None.

**Comment by magnusbaeck** [comment]
Perhaps the code for generating a routing key should be a method in the Eiffel event class? That way those who use eiffelib for constructing and validating events but sending them using other means can make use of the routing key generation.

**Comment by t-persson** [comment]
I agree with having None be a "magic kwarg value" and adding a deprecation warning if the kwarg value is not None.

I also agree with having the routing key generation in the event class
