### ISSUE TITLE
replace hardcoded event type name with __class__.__name__ for event class

### ISSUE THREAD

**Issue by jgse** [eiffel-community/eiffel-pythonlib#45]
### Description
```python
class EiffelActivityCanceledEvent(EiffelBaseEvent):
    """Eiffel activity canceled event."""

    version = "3.1.0"

    def __init__(self, *args, **kwargs):
        """Initialize data, meta and links."""
        super(EiffelActivityCanceledEvent, self).__init__(*args, **kwargs)
        self.meta = EiffelBaseMeta("EiffelActivityCanceledEvent", self.version) ### replace string "EiffelActivityCanceledEvent" with self.__class__.__name__
        self.links = EiffelActivityCanceledLink()
        self.data = EiffelActivityCanceledData()
```

the `self.meta = EiffelBaseMeta("EiffelActivityCanceledEvent", self.version)` can be replaced with `self.meta = EiffelBaseMeta(self.__class__.__name__, self.version)`

**Comment by EmanIsmail** [comment]
I would like to contribute with this issue.

**Comment by t-persson** [comment]
> I would like to contribute with this issue.

Go for it :)

**Comment by EmanIsmail** [comment]
@t-persson Could you grant me access rights to push new branch?

**Comment by t-persson** [comment]
> @t-persson Could you grant me access rights to push new branch?

We do not give push rights on the main repository. Please read the contributing document here: https://github.com/eiffel-community/.github/blob/master/CONTRIBUTING.md#how-to-contribute
