### ISSUE TITLE
Dependency to jsonschema is really old

### ISSUE THREAD

**Issue by MartinWallgren** [eiffel-community/eiffel-pythonlib#54]
### Description
It's not possible to use this lib if you have requirements to jsonschema >=4.0.0.
The release date for jsonschema 4.0.1 was Sep 30, 2021.

### Motivation
17 months is plenty of time to upgrade, and your clients might need software that relies on jsonschema 4.

### Exemplification
Package A depends on jsonschema >4.0.0

Package B depends on package A

Package B also want to use eiffellib, but that is impossible due to jsonschema verision constraints.

### Benefits
More people can use this lib.

### Possible Drawbacks
jsonschema >4 might not be compatible.

**Comment by magnusbaeck** [comment]
We should close this issue since #55 has been merged, right?
